# Site settings
title: macaron blog
email: yeaseul.parky@gmail.com
description: >
  a personal blog about life in Paris by Léa 
baseurl: 
url: bon.macaron.world
github_username:  earlgreymacaron

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  quotidien:
    output: true
    permalink: /quotidien/:path/

plugins: [jekyll-paginate]
